#!/bin/bash

case "$1" in
    configure)

function xsl_replace
{
#param 1 path
#param 2 file
#param 3 snippet
TEMP=$(mktemp --tmpdir=/tmp)
OUT=$(mktemp --tmpdir=/tmp)

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">
<xsl:apply-templates/>
</xsl:template>

<xsl:template match="node() | @*">
<xsl:copy>
<xsl:apply-templates select="node() | @*"/>
</xsl:copy>
</xsl:template>

<xsl:template match="'$1'">' > $TEMP

echo "$3" >> $TEMP

echo '</xsl:template>

</xsl:stylesheet> ' >> $TEMP

xsltproc $TEMP $2 > $OUT
if [ -s "$OUT" ]; then
cp $OUT $2
fi
}

FILE1="/usr/share/xbmc/system/keymaps/keyboard.xml"
FILE1_PATH1="/keymap/LoginScreen/keyboard/end[1]"
FILE1_PATH2="/keymap/Home/keyboard/end[1]"
FILE1_REPLACE="<end>XBMC.RunScript(special://xbmc/addons/script.shutdownvdr/default.py)</end>"

FILE2="/usr/share/xbmc/system/keymaps/remote.xml"
FILE2_PATH="/keymap/global/remote/power[1]"
FILE2_REPLACE="<power>XBMC.RunScript(special://xbmc/addons/script.shutdownvdr/default.py)</power>"

FILE3="/usr/share/xbmc/system/keymaps/joystick.Harmony.xml"
FILE3_PATH="/keymap/global/joystick[1]/button[@id='66']"
FILE3_REPLACE="<button id=\"66\">XBMC.RunScript(special://xbmc/addons/script.shutdownvdr/default.py)</button>"

FILE4="/usr/share/xbmc/addons/skin.confluence/720p/DialogButtonMenu.xml"
FILE4_PATH="/window[id='111']/controls/control[@id='9000']/control[@id='2']/onclick"
FILE4_REPLACE="<onclick>XBMC.RunScript(special://xbmc/script.shutdownvdr/default.py)</onclick>"

xsl_replace "$FILE1_PATH1" "$FILE1" "$FILE1_REPLACE"
xsl_replace "$FILE1_PATH2" "$FILE1" "$FILE1_REPLACE"
xsl_replace "$FILE2_PATH" "$FILE2" "$FILE2_REPLACE"
xsl_replace "$FILE3_PATH" "$FILE3" "$FILE3_REPLACE"
xsl_replace "$FILE4_PATH" "$FILE4" "$FILE4_REPLACE"

        ;;
esac
